# Generated by Django 5.2.4 on 2025-07-15 11:50

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(validators=[django.core.validators.MinLengthValidator(3), django.core.validators.MaxLengthValidator(100)])),
                ('summary', models.TextField()),
                ('start_date', models.DateField()),
                ('duration', models.SmallIntegerField(default=1, help_text='*Duration in days is expected.')),
                ('img_url', models.URLField(blank=True, null=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='traveler.traveler')),
            ],
        ),
    ]
